// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/timerwheel.proto

package cn.spawn.timerwheel.proto;

public interface AddTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:model.AddTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();
}
