// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/timerwheel.proto

package cn.spawn.timerwheel.proto;

/**
 * Protobuf type {@code model.AddTaskRequest}
 */
public  final class AddTaskRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.AddTaskRequest)
    AddTaskRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AddTaskRequest.newBuilder() to construct.
  private AddTaskRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AddTaskRequest() {
    delayTasks_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AddTaskRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AddTaskRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              delayTasks_ = new java.util.ArrayList<cn.spawn.timerwheel.proto.DelayTaskModel>();
              mutable_bitField0_ |= 0x00000001;
            }
            delayTasks_.add(
                input.readMessage(cn.spawn.timerwheel.proto.DelayTaskModel.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        delayTasks_ = java.util.Collections.unmodifiableList(delayTasks_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.spawn.timerwheel.proto.TimerWheelRpcService.internal_static_model_AddTaskRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.spawn.timerwheel.proto.TimerWheelRpcService.internal_static_model_AddTaskRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.spawn.timerwheel.proto.AddTaskRequest.class, cn.spawn.timerwheel.proto.AddTaskRequest.Builder.class);
  }

  public static final int DELAYTASKS_FIELD_NUMBER = 1;
  private java.util.List<cn.spawn.timerwheel.proto.DelayTaskModel> delayTasks_;
  /**
   * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
   */
  public java.util.List<cn.spawn.timerwheel.proto.DelayTaskModel> getDelayTasksList() {
    return delayTasks_;
  }
  /**
   * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
   */
  public java.util.List<? extends cn.spawn.timerwheel.proto.DelayTaskModelOrBuilder> 
      getDelayTasksOrBuilderList() {
    return delayTasks_;
  }
  /**
   * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
   */
  public int getDelayTasksCount() {
    return delayTasks_.size();
  }
  /**
   * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
   */
  public cn.spawn.timerwheel.proto.DelayTaskModel getDelayTasks(int index) {
    return delayTasks_.get(index);
  }
  /**
   * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
   */
  public cn.spawn.timerwheel.proto.DelayTaskModelOrBuilder getDelayTasksOrBuilder(
      int index) {
    return delayTasks_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < delayTasks_.size(); i++) {
      output.writeMessage(1, delayTasks_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < delayTasks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, delayTasks_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.spawn.timerwheel.proto.AddTaskRequest)) {
      return super.equals(obj);
    }
    cn.spawn.timerwheel.proto.AddTaskRequest other = (cn.spawn.timerwheel.proto.AddTaskRequest) obj;

    if (!getDelayTasksList()
        .equals(other.getDelayTasksList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDelayTasksCount() > 0) {
      hash = (37 * hash) + DELAYTASKS_FIELD_NUMBER;
      hash = (53 * hash) + getDelayTasksList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.spawn.timerwheel.proto.AddTaskRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.spawn.timerwheel.proto.AddTaskRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.spawn.timerwheel.proto.AddTaskRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.spawn.timerwheel.proto.AddTaskRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.spawn.timerwheel.proto.AddTaskRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.spawn.timerwheel.proto.AddTaskRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.spawn.timerwheel.proto.AddTaskRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.spawn.timerwheel.proto.AddTaskRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.spawn.timerwheel.proto.AddTaskRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.spawn.timerwheel.proto.AddTaskRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.spawn.timerwheel.proto.AddTaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.spawn.timerwheel.proto.AddTaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.spawn.timerwheel.proto.AddTaskRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.AddTaskRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.AddTaskRequest)
      cn.spawn.timerwheel.proto.AddTaskRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.spawn.timerwheel.proto.TimerWheelRpcService.internal_static_model_AddTaskRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.spawn.timerwheel.proto.TimerWheelRpcService.internal_static_model_AddTaskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.spawn.timerwheel.proto.AddTaskRequest.class, cn.spawn.timerwheel.proto.AddTaskRequest.Builder.class);
    }

    // Construct using cn.spawn.timerwheel.proto.AddTaskRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDelayTasksFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (delayTasksBuilder_ == null) {
        delayTasks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        delayTasksBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.spawn.timerwheel.proto.TimerWheelRpcService.internal_static_model_AddTaskRequest_descriptor;
    }

    @java.lang.Override
    public cn.spawn.timerwheel.proto.AddTaskRequest getDefaultInstanceForType() {
      return cn.spawn.timerwheel.proto.AddTaskRequest.getDefaultInstance();
    }

    @java.lang.Override
    public cn.spawn.timerwheel.proto.AddTaskRequest build() {
      cn.spawn.timerwheel.proto.AddTaskRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.spawn.timerwheel.proto.AddTaskRequest buildPartial() {
      cn.spawn.timerwheel.proto.AddTaskRequest result = new cn.spawn.timerwheel.proto.AddTaskRequest(this);
      int from_bitField0_ = bitField0_;
      if (delayTasksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          delayTasks_ = java.util.Collections.unmodifiableList(delayTasks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.delayTasks_ = delayTasks_;
      } else {
        result.delayTasks_ = delayTasksBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.spawn.timerwheel.proto.AddTaskRequest) {
        return mergeFrom((cn.spawn.timerwheel.proto.AddTaskRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.spawn.timerwheel.proto.AddTaskRequest other) {
      if (other == cn.spawn.timerwheel.proto.AddTaskRequest.getDefaultInstance()) return this;
      if (delayTasksBuilder_ == null) {
        if (!other.delayTasks_.isEmpty()) {
          if (delayTasks_.isEmpty()) {
            delayTasks_ = other.delayTasks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDelayTasksIsMutable();
            delayTasks_.addAll(other.delayTasks_);
          }
          onChanged();
        }
      } else {
        if (!other.delayTasks_.isEmpty()) {
          if (delayTasksBuilder_.isEmpty()) {
            delayTasksBuilder_.dispose();
            delayTasksBuilder_ = null;
            delayTasks_ = other.delayTasks_;
            bitField0_ = (bitField0_ & ~0x00000001);
            delayTasksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDelayTasksFieldBuilder() : null;
          } else {
            delayTasksBuilder_.addAllMessages(other.delayTasks_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.spawn.timerwheel.proto.AddTaskRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.spawn.timerwheel.proto.AddTaskRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<cn.spawn.timerwheel.proto.DelayTaskModel> delayTasks_ =
      java.util.Collections.emptyList();
    private void ensureDelayTasksIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        delayTasks_ = new java.util.ArrayList<cn.spawn.timerwheel.proto.DelayTaskModel>(delayTasks_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.spawn.timerwheel.proto.DelayTaskModel, cn.spawn.timerwheel.proto.DelayTaskModel.Builder, cn.spawn.timerwheel.proto.DelayTaskModelOrBuilder> delayTasksBuilder_;

    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public java.util.List<cn.spawn.timerwheel.proto.DelayTaskModel> getDelayTasksList() {
      if (delayTasksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(delayTasks_);
      } else {
        return delayTasksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public int getDelayTasksCount() {
      if (delayTasksBuilder_ == null) {
        return delayTasks_.size();
      } else {
        return delayTasksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public cn.spawn.timerwheel.proto.DelayTaskModel getDelayTasks(int index) {
      if (delayTasksBuilder_ == null) {
        return delayTasks_.get(index);
      } else {
        return delayTasksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public Builder setDelayTasks(
        int index, cn.spawn.timerwheel.proto.DelayTaskModel value) {
      if (delayTasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDelayTasksIsMutable();
        delayTasks_.set(index, value);
        onChanged();
      } else {
        delayTasksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public Builder setDelayTasks(
        int index, cn.spawn.timerwheel.proto.DelayTaskModel.Builder builderForValue) {
      if (delayTasksBuilder_ == null) {
        ensureDelayTasksIsMutable();
        delayTasks_.set(index, builderForValue.build());
        onChanged();
      } else {
        delayTasksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public Builder addDelayTasks(cn.spawn.timerwheel.proto.DelayTaskModel value) {
      if (delayTasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDelayTasksIsMutable();
        delayTasks_.add(value);
        onChanged();
      } else {
        delayTasksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public Builder addDelayTasks(
        int index, cn.spawn.timerwheel.proto.DelayTaskModel value) {
      if (delayTasksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDelayTasksIsMutable();
        delayTasks_.add(index, value);
        onChanged();
      } else {
        delayTasksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public Builder addDelayTasks(
        cn.spawn.timerwheel.proto.DelayTaskModel.Builder builderForValue) {
      if (delayTasksBuilder_ == null) {
        ensureDelayTasksIsMutable();
        delayTasks_.add(builderForValue.build());
        onChanged();
      } else {
        delayTasksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public Builder addDelayTasks(
        int index, cn.spawn.timerwheel.proto.DelayTaskModel.Builder builderForValue) {
      if (delayTasksBuilder_ == null) {
        ensureDelayTasksIsMutable();
        delayTasks_.add(index, builderForValue.build());
        onChanged();
      } else {
        delayTasksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public Builder addAllDelayTasks(
        java.lang.Iterable<? extends cn.spawn.timerwheel.proto.DelayTaskModel> values) {
      if (delayTasksBuilder_ == null) {
        ensureDelayTasksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, delayTasks_);
        onChanged();
      } else {
        delayTasksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public Builder clearDelayTasks() {
      if (delayTasksBuilder_ == null) {
        delayTasks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        delayTasksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public Builder removeDelayTasks(int index) {
      if (delayTasksBuilder_ == null) {
        ensureDelayTasksIsMutable();
        delayTasks_.remove(index);
        onChanged();
      } else {
        delayTasksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public cn.spawn.timerwheel.proto.DelayTaskModel.Builder getDelayTasksBuilder(
        int index) {
      return getDelayTasksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public cn.spawn.timerwheel.proto.DelayTaskModelOrBuilder getDelayTasksOrBuilder(
        int index) {
      if (delayTasksBuilder_ == null) {
        return delayTasks_.get(index);  } else {
        return delayTasksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public java.util.List<? extends cn.spawn.timerwheel.proto.DelayTaskModelOrBuilder> 
         getDelayTasksOrBuilderList() {
      if (delayTasksBuilder_ != null) {
        return delayTasksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(delayTasks_);
      }
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public cn.spawn.timerwheel.proto.DelayTaskModel.Builder addDelayTasksBuilder() {
      return getDelayTasksFieldBuilder().addBuilder(
          cn.spawn.timerwheel.proto.DelayTaskModel.getDefaultInstance());
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public cn.spawn.timerwheel.proto.DelayTaskModel.Builder addDelayTasksBuilder(
        int index) {
      return getDelayTasksFieldBuilder().addBuilder(
          index, cn.spawn.timerwheel.proto.DelayTaskModel.getDefaultInstance());
    }
    /**
     * <code>repeated .model.DelayTaskModel delayTasks = 1;</code>
     */
    public java.util.List<cn.spawn.timerwheel.proto.DelayTaskModel.Builder> 
         getDelayTasksBuilderList() {
      return getDelayTasksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        cn.spawn.timerwheel.proto.DelayTaskModel, cn.spawn.timerwheel.proto.DelayTaskModel.Builder, cn.spawn.timerwheel.proto.DelayTaskModelOrBuilder> 
        getDelayTasksFieldBuilder() {
      if (delayTasksBuilder_ == null) {
        delayTasksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            cn.spawn.timerwheel.proto.DelayTaskModel, cn.spawn.timerwheel.proto.DelayTaskModel.Builder, cn.spawn.timerwheel.proto.DelayTaskModelOrBuilder>(
                delayTasks_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        delayTasks_ = null;
      }
      return delayTasksBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.AddTaskRequest)
  }

  // @@protoc_insertion_point(class_scope:model.AddTaskRequest)
  private static final cn.spawn.timerwheel.proto.AddTaskRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.spawn.timerwheel.proto.AddTaskRequest();
  }

  public static cn.spawn.timerwheel.proto.AddTaskRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AddTaskRequest>
      PARSER = new com.google.protobuf.AbstractParser<AddTaskRequest>() {
    @java.lang.Override
    public AddTaskRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AddTaskRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AddTaskRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AddTaskRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.spawn.timerwheel.proto.AddTaskRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

