// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/timerwheel.proto

package cn.spawn.timerwheel.proto;

/**
 * Protobuf type {@code model.DelayTaskModel}
 */
public  final class DelayTaskModel extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:model.DelayTaskModel)
    DelayTaskModelOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DelayTaskModel.newBuilder() to construct.
  private DelayTaskModel(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DelayTaskModel() {
    key_ = "";
    monitorRule_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DelayTaskModel();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DelayTaskModel(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            key_ = s;
            break;
          }
          case 16: {

            delay_ = input.readInt32();
            break;
          }
          case 24: {

            circle_ = input.readInt32();
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            monitorRule_ = s;
            break;
          }
          case 40: {

            processTime_ = input.readInt64();
            break;
          }
          case 48: {

            timestamp_ = input.readInt64();
            break;
          }
          case 56: {

            expiredTime_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cn.spawn.timerwheel.proto.TimerWheelRpcService.internal_static_model_DelayTaskModel_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cn.spawn.timerwheel.proto.TimerWheelRpcService.internal_static_model_DelayTaskModel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cn.spawn.timerwheel.proto.DelayTaskModel.class, cn.spawn.timerwheel.proto.DelayTaskModel.Builder.class);
  }

  public static final int KEY_FIELD_NUMBER = 1;
  private volatile java.lang.Object key_;
  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DELAY_FIELD_NUMBER = 2;
  private int delay_;
  /**
   * <code>int32 delay = 2;</code>
   * @return The delay.
   */
  public int getDelay() {
    return delay_;
  }

  public static final int CIRCLE_FIELD_NUMBER = 3;
  private int circle_;
  /**
   * <code>int32 circle = 3;</code>
   * @return The circle.
   */
  public int getCircle() {
    return circle_;
  }

  public static final int MONITORRULE_FIELD_NUMBER = 4;
  private volatile java.lang.Object monitorRule_;
  /**
   * <code>string monitorRule = 4;</code>
   * @return The monitorRule.
   */
  public java.lang.String getMonitorRule() {
    java.lang.Object ref = monitorRule_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      monitorRule_ = s;
      return s;
    }
  }
  /**
   * <code>string monitorRule = 4;</code>
   * @return The bytes for monitorRule.
   */
  public com.google.protobuf.ByteString
      getMonitorRuleBytes() {
    java.lang.Object ref = monitorRule_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      monitorRule_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROCESSTIME_FIELD_NUMBER = 5;
  private long processTime_;
  /**
   * <code>int64 processTime = 5;</code>
   * @return The processTime.
   */
  public long getProcessTime() {
    return processTime_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 6;</code>
   * @return The timestamp.
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int EXPIREDTIME_FIELD_NUMBER = 7;
  private long expiredTime_;
  /**
   * <code>int64 expiredTime = 7;</code>
   * @return The expiredTime.
   */
  public long getExpiredTime() {
    return expiredTime_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, key_);
    }
    if (delay_ != 0) {
      output.writeInt32(2, delay_);
    }
    if (circle_ != 0) {
      output.writeInt32(3, circle_);
    }
    if (!getMonitorRuleBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, monitorRule_);
    }
    if (processTime_ != 0L) {
      output.writeInt64(5, processTime_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(6, timestamp_);
    }
    if (expiredTime_ != 0L) {
      output.writeInt64(7, expiredTime_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, key_);
    }
    if (delay_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, delay_);
    }
    if (circle_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, circle_);
    }
    if (!getMonitorRuleBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, monitorRule_);
    }
    if (processTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, processTime_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, timestamp_);
    }
    if (expiredTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, expiredTime_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cn.spawn.timerwheel.proto.DelayTaskModel)) {
      return super.equals(obj);
    }
    cn.spawn.timerwheel.proto.DelayTaskModel other = (cn.spawn.timerwheel.proto.DelayTaskModel) obj;

    if (!getKey()
        .equals(other.getKey())) return false;
    if (getDelay()
        != other.getDelay()) return false;
    if (getCircle()
        != other.getCircle()) return false;
    if (!getMonitorRule()
        .equals(other.getMonitorRule())) return false;
    if (getProcessTime()
        != other.getProcessTime()) return false;
    if (getTimestamp()
        != other.getTimestamp()) return false;
    if (getExpiredTime()
        != other.getExpiredTime()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    hash = (37 * hash) + DELAY_FIELD_NUMBER;
    hash = (53 * hash) + getDelay();
    hash = (37 * hash) + CIRCLE_FIELD_NUMBER;
    hash = (53 * hash) + getCircle();
    hash = (37 * hash) + MONITORRULE_FIELD_NUMBER;
    hash = (53 * hash) + getMonitorRule().hashCode();
    hash = (37 * hash) + PROCESSTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getProcessTime());
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (37 * hash) + EXPIREDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpiredTime());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cn.spawn.timerwheel.proto.DelayTaskModel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.spawn.timerwheel.proto.DelayTaskModel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.spawn.timerwheel.proto.DelayTaskModel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.spawn.timerwheel.proto.DelayTaskModel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.spawn.timerwheel.proto.DelayTaskModel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cn.spawn.timerwheel.proto.DelayTaskModel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cn.spawn.timerwheel.proto.DelayTaskModel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.spawn.timerwheel.proto.DelayTaskModel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.spawn.timerwheel.proto.DelayTaskModel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static cn.spawn.timerwheel.proto.DelayTaskModel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cn.spawn.timerwheel.proto.DelayTaskModel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static cn.spawn.timerwheel.proto.DelayTaskModel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cn.spawn.timerwheel.proto.DelayTaskModel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code model.DelayTaskModel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:model.DelayTaskModel)
      cn.spawn.timerwheel.proto.DelayTaskModelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.spawn.timerwheel.proto.TimerWheelRpcService.internal_static_model_DelayTaskModel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.spawn.timerwheel.proto.TimerWheelRpcService.internal_static_model_DelayTaskModel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.spawn.timerwheel.proto.DelayTaskModel.class, cn.spawn.timerwheel.proto.DelayTaskModel.Builder.class);
    }

    // Construct using cn.spawn.timerwheel.proto.DelayTaskModel.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      key_ = "";

      delay_ = 0;

      circle_ = 0;

      monitorRule_ = "";

      processTime_ = 0L;

      timestamp_ = 0L;

      expiredTime_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cn.spawn.timerwheel.proto.TimerWheelRpcService.internal_static_model_DelayTaskModel_descriptor;
    }

    @java.lang.Override
    public cn.spawn.timerwheel.proto.DelayTaskModel getDefaultInstanceForType() {
      return cn.spawn.timerwheel.proto.DelayTaskModel.getDefaultInstance();
    }

    @java.lang.Override
    public cn.spawn.timerwheel.proto.DelayTaskModel build() {
      cn.spawn.timerwheel.proto.DelayTaskModel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cn.spawn.timerwheel.proto.DelayTaskModel buildPartial() {
      cn.spawn.timerwheel.proto.DelayTaskModel result = new cn.spawn.timerwheel.proto.DelayTaskModel(this);
      result.key_ = key_;
      result.delay_ = delay_;
      result.circle_ = circle_;
      result.monitorRule_ = monitorRule_;
      result.processTime_ = processTime_;
      result.timestamp_ = timestamp_;
      result.expiredTime_ = expiredTime_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cn.spawn.timerwheel.proto.DelayTaskModel) {
        return mergeFrom((cn.spawn.timerwheel.proto.DelayTaskModel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cn.spawn.timerwheel.proto.DelayTaskModel other) {
      if (other == cn.spawn.timerwheel.proto.DelayTaskModel.getDefaultInstance()) return this;
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        onChanged();
      }
      if (other.getDelay() != 0) {
        setDelay(other.getDelay());
      }
      if (other.getCircle() != 0) {
        setCircle(other.getCircle());
      }
      if (!other.getMonitorRule().isEmpty()) {
        monitorRule_ = other.monitorRule_;
        onChanged();
      }
      if (other.getProcessTime() != 0L) {
        setProcessTime(other.getProcessTime());
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      if (other.getExpiredTime() != 0L) {
        setExpiredTime(other.getExpiredTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      cn.spawn.timerwheel.proto.DelayTaskModel parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (cn.spawn.timerwheel.proto.DelayTaskModel) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object key_ = "";
    /**
     * <code>string key = 1;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key = 1;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }
    /**
     * <code>string key = 1;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      key_ = value;
      onChanged();
      return this;
    }

    private int delay_ ;
    /**
     * <code>int32 delay = 2;</code>
     * @return The delay.
     */
    public int getDelay() {
      return delay_;
    }
    /**
     * <code>int32 delay = 2;</code>
     * @param value The delay to set.
     * @return This builder for chaining.
     */
    public Builder setDelay(int value) {
      
      delay_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 delay = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDelay() {
      
      delay_ = 0;
      onChanged();
      return this;
    }

    private int circle_ ;
    /**
     * <code>int32 circle = 3;</code>
     * @return The circle.
     */
    public int getCircle() {
      return circle_;
    }
    /**
     * <code>int32 circle = 3;</code>
     * @param value The circle to set.
     * @return This builder for chaining.
     */
    public Builder setCircle(int value) {
      
      circle_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 circle = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCircle() {
      
      circle_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object monitorRule_ = "";
    /**
     * <code>string monitorRule = 4;</code>
     * @return The monitorRule.
     */
    public java.lang.String getMonitorRule() {
      java.lang.Object ref = monitorRule_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        monitorRule_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string monitorRule = 4;</code>
     * @return The bytes for monitorRule.
     */
    public com.google.protobuf.ByteString
        getMonitorRuleBytes() {
      java.lang.Object ref = monitorRule_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        monitorRule_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string monitorRule = 4;</code>
     * @param value The monitorRule to set.
     * @return This builder for chaining.
     */
    public Builder setMonitorRule(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      monitorRule_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string monitorRule = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMonitorRule() {
      
      monitorRule_ = getDefaultInstance().getMonitorRule();
      onChanged();
      return this;
    }
    /**
     * <code>string monitorRule = 4;</code>
     * @param value The bytes for monitorRule to set.
     * @return This builder for chaining.
     */
    public Builder setMonitorRuleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      monitorRule_ = value;
      onChanged();
      return this;
    }

    private long processTime_ ;
    /**
     * <code>int64 processTime = 5;</code>
     * @return The processTime.
     */
    public long getProcessTime() {
      return processTime_;
    }
    /**
     * <code>int64 processTime = 5;</code>
     * @param value The processTime to set.
     * @return This builder for chaining.
     */
    public Builder setProcessTime(long value) {
      
      processTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 processTime = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessTime() {
      
      processTime_ = 0L;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 6;</code>
     * @return The timestamp.
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private long expiredTime_ ;
    /**
     * <code>int64 expiredTime = 7;</code>
     * @return The expiredTime.
     */
    public long getExpiredTime() {
      return expiredTime_;
    }
    /**
     * <code>int64 expiredTime = 7;</code>
     * @param value The expiredTime to set.
     * @return This builder for chaining.
     */
    public Builder setExpiredTime(long value) {
      
      expiredTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 expiredTime = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpiredTime() {
      
      expiredTime_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:model.DelayTaskModel)
  }

  // @@protoc_insertion_point(class_scope:model.DelayTaskModel)
  private static final cn.spawn.timerwheel.proto.DelayTaskModel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cn.spawn.timerwheel.proto.DelayTaskModel();
  }

  public static cn.spawn.timerwheel.proto.DelayTaskModel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DelayTaskModel>
      PARSER = new com.google.protobuf.AbstractParser<DelayTaskModel>() {
    @java.lang.Override
    public DelayTaskModel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DelayTaskModel(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DelayTaskModel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DelayTaskModel> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cn.spawn.timerwheel.proto.DelayTaskModel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

