// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/timerwheel.proto

package cn.spawn.timerwheel.proto;

public final class TimerWheelRpcService {
  private TimerWheelRpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_DelayTaskModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_DelayTaskModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_AddTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_AddTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_model_AddTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_model_AddTaskResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto/timerwheel.proto\022\005model\"\216\001\n\016Dela" +
      "yTaskModel\022\013\n\003key\030\001 \001(\t\022\r\n\005delay\030\002 \001(\005\022\016" +
      "\n\006circle\030\003 \001(\005\022\023\n\013monitorRule\030\004 \001(\t\022\023\n\013p" +
      "rocessTime\030\005 \001(\003\022\021\n\ttimestamp\030\006 \001(\003\022\023\n\013e" +
      "xpiredTime\030\007 \001(\003\";\n\016AddTaskRequest\022)\n\nde" +
      "layTasks\030\001 \003(\0132\025.model.DelayTaskModel\"\037\n" +
      "\017AddTaskResponse\022\014\n\004code\030\001 \001(\0052L\n\021TimerW" +
      "heelService\0227\n\004Send\022\025.model.AddTaskReque" +
      "st\032\026.model.AddTaskResponse\"\000B3\n\031cn.spawn" +
      ".timerwheel.protoB\024TimerWheelRpcServiceP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_model_DelayTaskModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_model_DelayTaskModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_DelayTaskModel_descriptor,
        new java.lang.String[] { "Key", "Delay", "Circle", "MonitorRule", "ProcessTime", "Timestamp", "ExpiredTime", });
    internal_static_model_AddTaskRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_model_AddTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_AddTaskRequest_descriptor,
        new java.lang.String[] { "DelayTasks", });
    internal_static_model_AddTaskResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_model_AddTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_model_AddTaskResponse_descriptor,
        new java.lang.String[] { "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
